# Generated by Django 5.1.1 on 2024-10-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='tilt',
            field=models.FloatField(default=0, null=True),
        ),
    ]
