# Generated by Django 5.1.1 on 2024-10-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='effective_temp',
            field=models.FloatField(),
        ),
    ]
