# Generated by Django 5.1.1 on 2024-10-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0002_scenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='show',
            field=models.IntegerField(default=1),
        ),
    ]
