# Generated by Django 5.1.1 on 2024-10-06 01:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0002_alter_planet_tilt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='scenarios',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
