# Generated by Django 5.1.1 on 2024-09-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0003_star_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='image',
        ),
        migrations.AddField(
            model_name='planet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
