# Generated by Django 5.1.1 on 2024-10-06 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0003_alter_author_scenarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='scenarios',
        ),
    ]
