# Generated by Django 5.1.1 on 2024-10-03 18:12

import exoplanet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0003_alter_author_name_alter_planet_name_alter_quest_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(error_messages={'unique': 'Already used!'}, max_length=100, primary_key=True, serialize=False, unique=True, validators=[exoplanet.models.validate_string]),
        ),
    ]
