# Generated by Django 5.1.1 on 2024-10-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0003_star_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='completed',
        ),
        migrations.AddField(
            model_name='quest',
            name='progress',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest',
            name='target',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest',
            name='type',
            field=models.CharField(default='mytype', max_length=100),
            preserve_default=False,
        ),
    ]
