# Generated by Django 5.1.1 on 2024-10-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0004_alter_author_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='created_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
