# Generated by Django 5.1.1 on 2024-10-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0004_remove_author_scenarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='eccentricity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
