# Generated by Django 5.1.1 on 2024-10-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0005_planet_created_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
