# Generated by Django 5.1.1 on 2024-10-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0006_quest_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
