# Generated by Django 5.1.1 on 2024-10-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0007_author_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='azi',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='star',
            name='dist',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='pol',
            field=models.FloatField(default=0),
        ),
    ]
