# Generated by Django 5.1.1 on 2024-10-05 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0008_star_azi_star_dist_star_pol'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='color',
            field=models.CharField(default='black', max_length=100),
        ),
    ]
