# Generated by Django 5.1.1 on 2024-10-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0009_planet_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='ESI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planet',
            name='SType',
            field=models.CharField(default='T', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='TType',
            field=models.CharField(default='T', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planet',
            name='density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planet',
            name='escape_velocity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planet',
            name='insolation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planet',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='habitable_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='habitable_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='luminosity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='star',
            name='visual_magnitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='eccentricity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='planet',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planet',
            name='semimajor_axis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='effective_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='radius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='star',
            name='spectral_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
