# Generated by Django 5.1.1 on 2024-10-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0010_planet_esi_planet_stype_planet_ttype_planet_density_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='atmospheric_composition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
