# Generated by Django 5.1.1 on 2024-10-05 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0011_planet_atmospheric_composition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='dist',
        ),
    ]
