# Generated by Django 5.1.1 on 2024-10-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0012_remove_star_dist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planet',
            old_name='escape_velocity',
            new_name='escape_vel',
        ),
    ]
