# Generated by Django 5.1.1 on 2024-10-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0013_rename_escape_velocity_planet_escape_vel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='created_by_user',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
