# Generated by Django 5.1.1 on 2024-10-05 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0014_alter_planet_created_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='created_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
