# Generated by Django 5.1.1 on 2024-10-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exoplanet', '0015_alter_planet_created_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='color',
        ),
    ]
